Repository UniversityOfSaskatchewanCMPT371/term-project-2025-team-3, pull requests merged in 2025-03, with the labels that each got.

#49 [Feature] Search Bar #24
  sk-vaccine-app/app/__tests__/index.test.tsx
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/components/__tests__/search-bar.test.tsx
  sk-vaccine-app/components/search-bar.tsx
  sk-vaccine-app/jest-setup.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/yarn.lock
Labels: Deliverable 3

#51 fixed the clinic data problem
  vaccine-data/clinic.json
  vaccine-data/scrape-clinic-info.js
Labels: Bug

#52 [Refactor] Home Page Restyling
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/app/settings.tsx
  sk-vaccine-app/components/closest-clinic-btn.tsx
  sk-vaccine-app/components/home-btn-chin.tsx
  sk-vaccine-app/components/home-square-btn.tsx
  sk-vaccine-app/components/settings-btn.tsx
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
Labels: Frontend, Styling, Deliverable 3

#54 Feature/clinic list page
  sk-vaccine-app/.env.development
  sk-vaccine-app/.env.production
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/app/display-clinic.tsx
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/components/card-link.tsx
  sk-vaccine-app/components/db-init.tsx
  sk-vaccine-app/hooks/clinicData.ts
  sk-vaccine-app/hooks/initDataSource.ts
  sk-vaccine-app/maestro/search-clinics.yaml
  sk-vaccine-app/myorm/base-entity.ts
  sk-vaccine-app/myorm/clinic-entity.ts
  sk-vaccine-app/myorm/decorators.ts
  sk-vaccine-app/myorm/vaccine-entity.ts
  sk-vaccine-app/services/clinicDataService.ts
  sk-vaccine-app/utils/constPaths.ts
  vaccine-data/.expo/README.md
  vaccine-data/.expo/settings.json
Labels: Feature, Clinic, Deliverable 3

#57 Tests/smoke tests
  .github/workflows/smoke-tests.yml
  sk-vaccine-app/maestro/smoke-tests/clinic-info.yaml
  sk-vaccine-app/maestro/smoke-tests/home.yaml
  sk-vaccine-app/maestro/smoke-tests/vaccine-info.yaml
Labels: Deliverable 3

#58 Feature/get vaccines
  sk-vaccine-app/app/_layout.tsx
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/hooks/__tests__/vaccineData.test.ts
  sk-vaccine-app/hooks/vaccineData.ts
  sk-vaccine-app/interfaces/iVaccineData.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/services/vaccineDataService.ts
  vaccine-data/clinic.json
Labels: Backend, Function, Deliverable 3

#65 Deliverable 3 Merge
  .github/workflows/build-android.yml
  .github/workflows/smoke-tests.yml
  sk-vaccine-app/.env.development
  sk-vaccine-app/.env.production
  sk-vaccine-app/app/__tests__/index.test.tsx
  sk-vaccine-app/app/_layout.tsx
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/app/display-clinic.tsx
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/app/settings.tsx
  sk-vaccine-app/app/vaccine-info.tsx
  sk-vaccine-app/components/__tests__/search-bar.test.tsx
  sk-vaccine-app/components/card-link.tsx
  sk-vaccine-app/components/closest-clinic-btn.tsx
  sk-vaccine-app/components/db-init.tsx
  sk-vaccine-app/components/home-btn-chin.tsx
  sk-vaccine-app/components/home-square-btn.tsx
  sk-vaccine-app/components/search-bar.tsx
  sk-vaccine-app/components/settings-btn.tsx
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/hooks/__tests__/vaccineData.test.ts
  sk-vaccine-app/hooks/clinicData.ts
  sk-vaccine-app/hooks/initDataSource.ts
  sk-vaccine-app/hooks/vaccineData.ts
  sk-vaccine-app/interfaces/iVaccineData.ts
  sk-vaccine-app/jest-setup.ts
  sk-vaccine-app/maestro/search-clinics.yaml
  sk-vaccine-app/myorm/base-entity.ts
  sk-vaccine-app/myorm/clinic-entity.ts
  sk-vaccine-app/myorm/decorators.ts
  sk-vaccine-app/myorm/vaccine-entity.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/services/clinicDataService.ts
  sk-vaccine-app/services/vaccineDataService.ts
  sk-vaccine-app/services/vaccineListService.data.json
  sk-vaccine-app/utils/config.ts
  sk-vaccine-app/utils/constPaths.ts
  sk-vaccine-app/yarn.lock
  vaccine-data/.expo/README.md
  vaccine-data/.expo/settings.json
  vaccine-data/clinic.json
  vaccine-data/scrape-clinic-info.js
Labels: Deliverable 3

#67 Added 10 tests for vaccineController, added error types and fixed a f…
  sk-vaccine-app/controllers/__tests__/vaccineDataController.test.ts
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/hooks/vaccineData.ts
  sk-vaccine-app/myorm/decorators.ts
  sk-vaccine-app/services/vaccineDataService.ts
  sk-vaccine-app/utils/ErrorTypes.ts
Labels: Vaccine, Deliverable 3, Tests

#86 [feature] Display Clinic Page
  sk-vaccine-app/app.json
  sk-vaccine-app/app/display-clinic.tsx
  sk-vaccine-app/components/__tests__/map.test.tsx
  sk-vaccine-app/components/map.tsx
  sk-vaccine-app/services/clinicDataService.ts
  sk-vaccine-app/utils/ErrorTypes.ts
Labels: Feature, Deliverable 4

#88 [FIx] Vaccines now update on startup and properly
  sk-vaccine-app/app/_layout.tsx
  sk-vaccine-app/app/vaccine-info.tsx
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/coverage/lcov-report/app/index.html
  sk-vaccine-app/coverage/lcov-report/app/index.tsx.html
  sk-vaccine-app/coverage/lcov-report/app/vaccine-info.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/card-link.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/closest-clinic-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/home-square-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/index.html
  sk-vaccine-app/coverage/lcov-report/components/search-bar.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/settings-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/controllers/index.html
  sk-vaccine-app/coverage/lcov-report/controllers/vaccineDataController.ts.html
  sk-vaccine-app/coverage/lcov-report/hooks/index.html
  sk-vaccine-app/coverage/lcov-report/hooks/locationData.ts.html
  sk-vaccine-app/coverage/lcov-report/hooks/vaccineData.ts.html
  sk-vaccine-app/coverage/lcov-report/myorm/base-entity.ts.html
  sk-vaccine-app/coverage/lcov-report/myorm/decorators.ts.html
  sk-vaccine-app/coverage/lcov-report/myorm/index.html
  sk-vaccine-app/coverage/lcov-report/myorm/vaccine-entity.ts.html
  sk-vaccine-app/coverage/lcov-report/services/clinicDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/services/index.html
  sk-vaccine-app/coverage/lcov-report/services/locationDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/services/vaccineDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/ErrorTypes.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/config.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/constPaths.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/index.html
  sk-vaccine-app/coverage/lcov-report/utils/logger.ts.html
  sk-vaccine-app/hooks/__tests__/vaccineData.test.ts
  sk-vaccine-app/hooks/vaccineData.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/services/vaccineListService.data.json
Labels: Bug, Backend, Vaccine, Deliverable 4

#90 [Feature] Adds a global COLOUR constant
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/utils/colours.ts
Labels: Feature, Quick, Styling, Deliverable 4

#93 sped up clinic info and updated tests
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/components/search-bar.tsx
  sk-vaccine-app/hooks/__tests__/clinicData.test.ts
  sk-vaccine-app/hooks/clinicData.ts
Labels: Feature, Deliverable 4

#96 fixed clinic search
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/hooks/clinicData.ts
Labels: Bug, Deliverable 4

#97 updated readme
  README.md
  images/clinic-map.png
  images/clinic.png
  images/clinics.png
  images/home.png
  images/vaccines.png
Labels: Quick

#100 [Feature/Fix] Vaccines are displaying and downloading
  .gitignore
  sk-vaccine-app/.gitignore
  sk-vaccine-app/app/display-vaccine.tsx
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/app/vaccine-info.tsx
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/coverage/clover.xml
  sk-vaccine-app/coverage/coverage-final.json
  sk-vaccine-app/coverage/lcov-report/app/index.html
  sk-vaccine-app/coverage/lcov-report/app/index.tsx.html
  sk-vaccine-app/coverage/lcov-report/app/vaccine-info.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/card-link.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/closest-clinic-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/home-square-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/index.html
  sk-vaccine-app/coverage/lcov-report/components/search-bar.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/settings-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/controllers/index.html
  sk-vaccine-app/coverage/lcov-report/controllers/vaccineDataController.ts.html
  sk-vaccine-app/coverage/lcov-report/hooks/index.html
  sk-vaccine-app/coverage/lcov-report/hooks/locationData.ts.html
  sk-vaccine-app/coverage/lcov-report/hooks/vaccineData.ts.html
  sk-vaccine-app/coverage/lcov-report/index.html
  sk-vaccine-app/coverage/lcov-report/myorm/base-entity.ts.html
  sk-vaccine-app/coverage/lcov-report/myorm/decorators.ts.html
  sk-vaccine-app/coverage/lcov-report/myorm/index.html
  sk-vaccine-app/coverage/lcov-report/myorm/vaccine-entity.ts.html
  sk-vaccine-app/coverage/lcov-report/services/clinicDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/services/index.html
  sk-vaccine-app/coverage/lcov-report/services/locationDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/services/vaccineDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/ErrorTypes.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/config.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/constPaths.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/index.html
  sk-vaccine-app/coverage/lcov-report/utils/logger.ts.html
  sk-vaccine-app/coverage/lcov.info
  sk-vaccine-app/hooks/vaccineData.ts
  sk-vaccine-app/interfaces/iVaccineData.ts
  sk-vaccine-app/myorm/base-entity.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/services/vaccineDataService.ts
  sk-vaccine-app/services/vaccineListService.data.json
  sk-vaccine-app/utils/ErrorTypes.ts
Labels: Backend, Vaccine, Function, Deliverable 4

#101 [Hot-Fix] Updated the Typedoc to include coverage testing. Also added a test for main pull request for typedoc
  .github/workflows/typedoc-test.yml
  .github/workflows/typedoc.yml
  .gitignore
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/app/vaccine-info.tsx
  sk-vaccine-app/coverage/clover.xml
  sk-vaccine-app/coverage/coverage-final.json
  sk-vaccine-app/coverage/lcov-report/base.css
  sk-vaccine-app/coverage/lcov-report/block-navigation.js
  sk-vaccine-app/coverage/lcov-report/favicon.png
  sk-vaccine-app/coverage/lcov-report/index.html
  sk-vaccine-app/coverage/lcov-report/prettify.css
  sk-vaccine-app/coverage/lcov-report/prettify.js
  sk-vaccine-app/coverage/lcov-report/sort-arrow-sprite.png
  sk-vaccine-app/coverage/lcov-report/sorter.js
  sk-vaccine-app/coverage/lcov.info
  sk-vaccine-app/typedoc.json
Labels: Hot Fix, Deliverable 4

#103 Refactor/header logo and app name
  sk-vaccine-app/app/_layout.tsx
  sk-vaccine-app/assets/images/NursingLogo.webp
Labels: Frontend, Styling, Deliverable 4

#105 [Hot-Fix] Removed coverage and updated the gitignore
  sk-vaccine-app/coverage/clover.xml
  sk-vaccine-app/coverage/coverage-final.json
  sk-vaccine-app/coverage/lcov-report/app/index.html
  sk-vaccine-app/coverage/lcov-report/app/index.tsx.html
  sk-vaccine-app/coverage/lcov-report/app/vaccine-info.tsx.html
  sk-vaccine-app/coverage/lcov-report/base.css
  sk-vaccine-app/coverage/lcov-report/block-navigation.js
  sk-vaccine-app/coverage/lcov-report/components/card-link.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/closest-clinic-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/home-square-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/index.html
  sk-vaccine-app/coverage/lcov-report/components/search-bar.tsx.html
  sk-vaccine-app/coverage/lcov-report/components/settings-btn.tsx.html
  sk-vaccine-app/coverage/lcov-report/controllers/index.html
  sk-vaccine-app/coverage/lcov-report/controllers/vaccineDataController.ts.html
  sk-vaccine-app/coverage/lcov-report/favicon.png
  sk-vaccine-app/coverage/lcov-report/hooks/index.html
  sk-vaccine-app/coverage/lcov-report/hooks/locationData.ts.html
  sk-vaccine-app/coverage/lcov-report/hooks/vaccineData.ts.html
  sk-vaccine-app/coverage/lcov-report/index.html
  sk-vaccine-app/coverage/lcov-report/myorm/base-entity.ts.html
  sk-vaccine-app/coverage/lcov-report/myorm/decorators.ts.html
  sk-vaccine-app/coverage/lcov-report/myorm/index.html
  sk-vaccine-app/coverage/lcov-report/myorm/vaccine-entity.ts.html
  sk-vaccine-app/coverage/lcov-report/prettify.css
  sk-vaccine-app/coverage/lcov-report/prettify.js
  sk-vaccine-app/coverage/lcov-report/services/clinicDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/services/index.html
  sk-vaccine-app/coverage/lcov-report/services/locationDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/services/vaccineDataService.ts.html
  sk-vaccine-app/coverage/lcov-report/sort-arrow-sprite.png
  sk-vaccine-app/coverage/lcov-report/sorter.js
  sk-vaccine-app/coverage/lcov-report/utils/ErrorTypes.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/config.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/constPaths.ts.html
  sk-vaccine-app/coverage/lcov-report/utils/index.html
  sk-vaccine-app/coverage/lcov-report/utils/logger.ts.html
  sk-vaccine-app/coverage/lcov.info
Labels: Hot Fix, Deliverable 4

#104 Deliverable 4 Feature Freeze
  .gitignore
  sk-vaccine-app/.gitignore
  sk-vaccine-app/app.json
  sk-vaccine-app/app/_layout.tsx
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/app/display-clinic.tsx
  sk-vaccine-app/app/display-vaccine.tsx
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/app/vaccine-info.tsx
  sk-vaccine-app/assets/fonts/MYRIADPRO-BOLD.OTF
  sk-vaccine-app/assets/fonts/MYRIADPRO-REGULAR.OTF
  sk-vaccine-app/assets/fonts/MYRIADPRO-SEMIBOLD.OTF
  sk-vaccine-app/assets/fonts/MinionPro-Bold.otf
  sk-vaccine-app/assets/fonts/MinionPro-Medium.otf
  sk-vaccine-app/assets/fonts/MinionPro-Regular.otf
  sk-vaccine-app/assets/fonts/MinionPro-Semibold.otf
  sk-vaccine-app/assets/fonts/MyriadPro-Light.otf
  sk-vaccine-app/assets/images/NursingLogo.webp
  sk-vaccine-app/components/__tests__/map.test.tsx
  sk-vaccine-app/components/map.tsx
  sk-vaccine-app/components/search-bar.tsx
  sk-vaccine-app/components/settings-btn.tsx
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/hooks/__tests__/clinicData.test.ts
  sk-vaccine-app/hooks/__tests__/vaccineData.test.ts
  sk-vaccine-app/hooks/clinicData.ts
  sk-vaccine-app/hooks/vaccineData.ts
  sk-vaccine-app/interfaces/iVaccineData.ts
  sk-vaccine-app/myorm/base-entity.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/react-native.config.js
  sk-vaccine-app/services/clinicDataService.ts
  sk-vaccine-app/services/vaccineDataService.ts
  sk-vaccine-app/services/vaccineListService.data.json
  sk-vaccine-app/utils/ErrorTypes.ts
  sk-vaccine-app/utils/colours.ts
Labels: Documentation, Frontend, Backend, Function, Styling, Deliverable 4

#108 [Tests] updateVaccineList() Tests as
  sk-vaccine-app/controllers/__tests__/vaccineDataController.test.ts
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/services/vaccineDataService.ts
  sk-vaccine-app/utils/ErrorTypes.ts
Labels: Deliverable 4, Tests

#110 [Testing] Added an in memory test db with sqlite3
  sk-vaccine-app/app.json
  sk-vaccine-app/controllers/__tests__/vaccineDataController.test.ts
  sk-vaccine-app/jest-setup.ts
  sk-vaccine-app/myorm/__tests__/decorators.test.ts
  sk-vaccine-app/myorm/base-entity.ts
  sk-vaccine-app/myorm/decorators.ts
  sk-vaccine-app/myorm/vaccine-entity.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/temp.db
  sk-vaccine-app/tsconfig.json
Labels: Feature, Deliverable 4, Tests

#111 wrote tests for clinic ui
  sk-vaccine-app/hooks/clinicData.ts
  sk-vaccine-app/maestro/view-clinic-by-addr.yml
  sk-vaccine-app/maestro/view-clinic-by-city.yml
  sk-vaccine-app/maestro/view-clinic-by-name.yml
Labels: Deliverable 4, Tests

#119 Fix/build yml
  .github/workflows/build-android.yml
Labels: Bug, Deliverable 5

#128 Feature/clinic distance
  .github/workflows/.vscode/settings.json
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/hooks/__tests__/clinicData.test.ts
  sk-vaccine-app/hooks/clinicData.ts
  sk-vaccine-app/interfaces/iLocationData.ts
  sk-vaccine-app/services/__tests__/locationDataService.test.ts
  sk-vaccine-app/services/locationDataService.ts
  vaccine-data/.gitignore
  vaccine-data/clinic.json
  vaccine-data/package-lock.json
  vaccine-data/package.json
  vaccine-data/plan.txt
  vaccine-data/scrape-clinic-info.js
  vaccine-data/scrape-clinic-info.ts
  vaccine-data/tsconfig.json
Labels: Feature, Deliverable 5

#129 Create scrape-vaccine-info.js
  vaccine-data/scrape-vaccine-info.js
Labels: Backend, Vaccine, Deliverable 5

#130 [Feature] Show closest clinic #125
  sk-vaccine-app/app/__tests__/index.test.tsx
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/app/display-clinic.tsx
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/app/vaccine-info.tsx
  sk-vaccine-app/components/closest-clinic-btn.tsx
  sk-vaccine-app/hooks/clinicData.ts
  sk-vaccine-app/utils/constPaths.ts
  vaccine-data/.vscode/settings.json
Labels: Feature, Deliverable 5

#132 [Bug/Refactor] Font sizing is dynamic | Updated some colous
  sk-vaccine-app/app/clinic-info.tsx
  sk-vaccine-app/app/display-clinic.tsx
  sk-vaccine-app/app/display-vaccine.tsx
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/app/vaccine-info.tsx
  sk-vaccine-app/components/card-link.tsx
  sk-vaccine-app/components/closest-clinic-btn.tsx
  sk-vaccine-app/components/home-square-btn.tsx
  sk-vaccine-app/components/search-bar.tsx
  sk-vaccine-app/utils/colours.ts
Labels: Bug, Frontend, Styling, Deliverable 5
