Repository UniversityOfSaskatchewanCMPT371/term-project-2025-team-3, pull requests merged in 2025-02, with the labels that each got.

#19 fixed expo blur version
  sk-vaccine-app/package.json
Labels: Bug, Deliverable 2

#21 Feature/location data
  sk-vaccine-app/.gitignore
  sk-vaccine-app/app.json
  sk-vaccine-app/app/__tests__/index.test.tsx
  sk-vaccine-app/hooks/__tests__/locationData.test.ts
  sk-vaccine-app/hooks/locationData.ts
  sk-vaccine-app/interfaces/iLocationData.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/services/__tests__/locationDataService.test.ts
  sk-vaccine-app/services/locationDataService.ts
  sk-vaccine-app/tsconfig.json
Labels: Deliverable 2

#27 Feature/clinic data Interfaces
  sk-vaccine-app/hooks/clinicData.ts
  sk-vaccine-app/interfaces/iClincData.ts
  sk-vaccine-app/services/clinicDataService.ts
Labels: Deliverable 2

#28 Feature/clinic data
  sk-vaccine-app/.gitignore
  sk-vaccine-app/app.json
  sk-vaccine-app/app/_layout.tsx
  sk-vaccine-app/app/index.tsx
  sk-vaccine-app/app/test.tsx
  sk-vaccine-app/bable.config.js
  sk-vaccine-app/components/db-init.tsx
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/hooks/__tests__/clinicData.test.ts
  sk-vaccine-app/hooks/__tests__/locationData.test.ts
  sk-vaccine-app/hooks/clinicData.ts
  sk-vaccine-app/hooks/initDataSource.ts
  sk-vaccine-app/hooks/locationData.ts
  sk-vaccine-app/interfaces/iClincData.ts
  sk-vaccine-app/interfaces/iClinicData.ts
  sk-vaccine-app/interfaces/iVaccineData.ts
  sk-vaccine-app/jest-setup.ts
  sk-vaccine-app/myorm/__tests__/base-entity.test.ts
  sk-vaccine-app/myorm/__tests__/decorators.test.ts
  sk-vaccine-app/myorm/base-entity.ts
  sk-vaccine-app/myorm/clinic-entity.ts
  sk-vaccine-app/myorm/decorators.ts
  sk-vaccine-app/myorm/vaccine-entity.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/package.json
  sk-vaccine-app/services/__tests__/clinicDataService.test.ts
  sk-vaccine-app/services/__tests__/locationDataService.test.ts
  sk-vaccine-app/services/__tests__/vaccineDataService.test.ts
  sk-vaccine-app/services/__tests__/vaccineDataServiceTest1.data.json
  sk-vaccine-app/services/__tests__/vaccineListService.data.json
  sk-vaccine-app/services/clinicDataService.ts
  sk-vaccine-app/services/locationDataService.ts
  sk-vaccine-app/services/vaccineDataService.ts
  sk-vaccine-app/tsconfig.json
  sk-vaccine-app/utils/ErrorTypes.ts
Labels: Feature, Clinic

#30 Feature/vaccine clinic data merge
  sk-vaccine-app/controllers/vaccineDataController.ts
  sk-vaccine-app/interfaces/iVaccineData.ts
  sk-vaccine-app/myorm/__tests__/decorators.test.ts
  sk-vaccine-app/myorm/decorators.ts
  sk-vaccine-app/myorm/vaccine-entity.ts
  sk-vaccine-app/package-lock.json
  sk-vaccine-app/services/__tests__/vaccineDataService.test.ts
  sk-vaccine-app/services/vaccineDataService.ts
Labels: Deliverable 2, Backend, Vaccine, Function
